# Generated by Django 3.2.4 on 2021-08-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('subspecies', models.CharField(max_length=50, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='profile_photo/')),
                ('birthday', models.DateField(null=True)),
                ('memorialday', models.DateField()),
                ('introduce', models.TextField(null=True)),
                ('season', models.CharField(max_length=10, null=True)),
                ('flowers', models.CharField(max_length=200, null=True)),
                ('gravestone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='csCenter',
            fields=[
                ('cs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('writer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50, unique=True)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VisiterBook',
            fields=[
                ('vs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visbook_title', models.CharField(max_length=100)),
                ('visbook_pub_date', models.DateTimeField()),
                ('visbook_body', models.TextField()),
                ('visbook_reply', models.TextField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.user')),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.animal')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.user')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diary_title', models.CharField(max_length=100)),
                ('diary_pub_date', models.DateTimeField()),
                ('diary_body', models.TextField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.animal')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.user')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbg.user'),
        ),
    ]
