# Generated by Django 3.2.5 on 2021-08-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_link',
        ),
    ]
