# Generated by Django 3.2.4 on 2021-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
