# Generated by Django 3.2.4 on 2021-08-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbg', '0002_auto_20210807_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbg.user'),
        ),
    ]
