# Generated by Django 3.2.4 on 2021-08-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbg', '0002_auto_20210811_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_link',
            field=models.URLField(null=True),
        ),
    ]
