# Generated by Django 3.2.4 on 2021-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbg', '0003_alter_user_user_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='animal_id',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='visiterbook',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='visiterbook',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='animal',
            name='diary_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='diary_pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='diary_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='gallery_listnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='visbook_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='visbook_pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='visbook_reply',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='visbook_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='VisiterBook',
        ),
    ]
